# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a21ae1f2e813e322a124c5f44f9dc3711a7bde3ebdbbb0ecd0862fbd87c6fdc59f60f9b04d86208c19370d0a059e0e7e8813c401321b248650929d04bba604a

test:
  secret_key_base: 5641871aff0951168a9d661809f6d4317c36f4c6ec876c2e862545ea3482e7b202c6d930ae7e6411bd6bcd8f6a6033c815eda39cb494625983bad78379794627

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
